### ISSUE TITLE
Add support for  'is:' operator

### ISSUE THREAD

**Issue by estilles** [GitbookIO/filterable#8]
Add support for querying `boolean` queries using the `is:xxx` syntax. I propose something like the following: 

``` js
var Filterable = require('filterable').Filterable;
var filterable = new Filterable({
  ...
  fields: {
    published: {
      type: Boolean
    },
    admin: {
      type: Boolean,
      alias: 'isAdmin'
    },
    gender: {
      type: String
    },
    male: {
      type: Boolean,
      query: 'gender:male'
    },
    female: {
      type: Boolean,
      query: 'gender:female'
    },
    age: {
      type: Number
    },
    minor: {
      type: Boolean,
      query: 'age:<18'
    },
  },
  ...
});
```

And `.query()` would yield:

``` js
filterable.query('is:published', function(err, query) {
    /*
    query.toMongo() == {
        "published": true
    }
    */
});

filterable.query("is:admin", function(err, query) {
    /*
    query.toMongo() == {
        "isAdmin": true
    }
    */
});

filterable.query('is:male', function(err, query) {
    /*
    query.toMongo() == {
        "gender": "male"
    }
    */
});

filterable.query('is:female', function(err, query) {
    /*
    query.toMongo() == {
        "gender": "female"
    }
    */
});

filterable.query('is:minor', function(err, query) {
    /*
    query.toMongo() == {
        "age": { "$lt": 18 }
    }
    */
});
```

The above is by no means an exhaustive description. If you're amenable to include this feature I would be willing to work on a PR.

<hr />

This is my progress so far:
- [x] refactor code to split groups into a reusable function
- [x] implement "is:" operator in `Query` class
- [x] add unit tests
- [ ] implement "is:" operator in `FitlerablePlugin()`.
- [ ] update README

**Comment by SamyPesse** [comment]
This could be a nice addition :+1: I'm open to include this feature if you make a PR.

**Comment by JohnnyEstilles** [comment]
I didn't realize until now that the implementation of the options pass to `Filterable` and `FilterablePlugin` or slightly different and incompattible. I was under the incorrect assumption they were identical.

I've already implemented this feature in the `Filterable` class. Need to figure out an elegant way to do so in `FilterablePlugin` as well.
<hr />
On a separate note, I also noticed you don't have any unit tests for `FilterablePlugin`, but that's something we should address in a separate issue, sometime in the near future.

**Comment by JohnnyEstilles** [comment]
@SamyPesse, in case you want to see my progress, you can check out this branch: [JohnnyEstilles:feature/is-operator](https://github.com/JohnnyEstilles/filterable/tree/feature/is-operator).

**Comment by SamyPesse** [comment]
Feel free to open a PR before it's ready, I'll merge it once you're ready but I can follow and comment your changes there :)

**Comment by JohnnyEstilles** [comment]
@SamyPesse, just out of curiosity, is there a reason the options object has used with `FilterablePlugin` is different than that of `Filterable`? It just seems to me that a consistent implementation would:

- simplify the code
- simplify unit testing
- make it easier to understand and use

Making the implementation consistent would be a breaking change, so I'm not by any means suggesting we do it not, but it's something we should consider along the road (maybe for `2.x`).

**Comment by SamyPesse** [comment]
It seems to me that `FilterablePlugin` is extracting fields infos from mongoose model, for example in our source code:

```js
authorSchema.plugin(filterable.mongoose, {
    fields: ["username", "name", "location"],
    tagsFields: [ "description" ]
});
```

**Comment by JohnnyEstilles** [comment]
I understand. And that perfectly alright if and when `FilterablePlugin` uses solely configuration information from the schema. However, as soon as we inject `alias`, `value` and now `query` configuration for each field, it seems awkward to use a format different from the one used with `Filterable`.

I propose the following backwards compatible solution:
- `fields` can be an array or an object hash
- when `fields` is an `array` map/convert as is currently done
- when `fields` is an `object` use as-is

Your thoughts?

**Comment by SamyPesse** [comment]
Yes it's a good idea :+1:

**Comment by JohnnyEstilles** [comment]
Excellent! Since this change will be backwards compatible you ca release in `1.1.0`. I will work on this after the unit tests for `FilterablePlugin` (issue #13).

**Comment by JohnnyEstilles** [comment]
@SamyPesse, would you be willing to `FilterablePlugin` in the "query" returned from `.search()` to make the plugin more testable? I suggest calling the property `.__filterable`.

**Comment by JohnnyEstilles** [comment]
@SamyPesse, please let me know if you would like me to continue work on this issue.
