### ISSUE TITLE
Possible inconstancies in operator inversion

### ISSUE THREAD

**Issue by JohnnyEstilles** [GitbookIO/filterable#9]
While working on a PR for issue #8 if found what I believe are inconstancies in the way some comparison operators are inverted. For example: `>=` inverts to `<=`, I posit it should invert to `<`. The way I see it `>=` is inclusive of the value its comparing, therefore the inverted operator should not, hence `<` and not `<=` (which does).

The following should be corrected:

Operator | Currently Inverts to | Should invert to
:----------: | :------------------------: | :-------------------:
>= | <= | <
> | < | <=
<= | >= | >
< | > | >=

If you agree I will submit a PR correcting this.

**Comment by SamyPesse** [comment]
Fixed by #10
